import Plant from '../models/Plant.js';
import db from '../config/connection.js';
import cleanDB from './cleanDB.js';

// Define growth type enum values
const PlantGrowthType = {
  NORMAL: 'normal',
  VERTICAL: 'vertical',
  VERTICAL_BEAN_PEA: 'vertical_bean_pea'
};

// Plant data from the client-side plantData.ts file, adapted for the database
const plantSeeds = [
  {
    plantName: 'Tomato',
    plantType: 'Vegetable',
    plantVariety: '',
    plantImage: '/images/tomato.png',
    plantWatering: 'Regular',
    plantLight: 'Full sun',
    plantSoil: 'Well-draining, rich in organic matter',
    plantFertilizer: 'Balanced fertilizer, higher in phosphorus when fruiting',
    plantHumidity: 'Moderate',
    plantTemperature: '65-85°F (18-29°C)',
    plantToxicity: 'Leaves and stems are toxic to pets',
    plantPests: 'Aphids, hornworms, whiteflies',
    plantDiseases: 'Blight, wilt, powdery mildew',
    spacing: 18,
    growthType: PlantGrowthType.VERTICAL,
    isVerticalGrower: true
  },
  {
    plantName: 'Carrot',
    plantType: 'Root vegetable',
    plantVariety: '',
    plantImage: '/images/carrot.png',
    plantWatering: 'Moderate',
    plantLight: 'Full sun',
    plantSoil: 'Loose, sandy, well-draining',
    plantFertilizer: 'Low nitrogen, high potassium',
    plantHumidity: 'Moderate',
    plantTemperature: '60-70°F (15-21°C)',
    plantToxicity: 'Non-toxic',
    plantPests: 'Carrot rust flies, nematodes',
    plantDiseases: 'Leaf blight, powdery mildew',
    spacing: 3,
    growthType: PlantGrowthType.NORMAL,
    isVerticalGrower: false
  },
  {
    plantName: 'Lettuce',
    plantType: 'Leafy green',
    plantVariety: '',
    plantImage: '/images/lettuce.png',
    plantWatering: 'Regular',
    plantLight: 'Partial shade',
    plantSoil: 'Rich, moist, well-draining',
    plantFertilizer: 'Nitrogen-rich fertilizer',
    plantHumidity: 'Moderate',
    plantTemperature: '45-75°F (7-24°C)',
    plantToxicity: 'Non-toxic',
    plantPests: 'Aphids, slugs, snails',
    plantDiseases: 'Downy mildew, bottom rot',
    spacing: 6,
    growthType: PlantGrowthType.NORMAL,
    isVerticalGrower: false
  },
  {
    plantName: 'Cucumber',
    plantType: 'Vegetable',
    plantVariety: '',
    plantImage: '/images/cucumber.png',
    plantWatering: 'Regular',
    plantLight: 'Full sun',
    plantSoil: 'Rich, well-draining',
    plantFertilizer: 'Balanced fertilizer',
    plantHumidity: 'Moderate to high',
    plantTemperature: '65-85°F (18-29°C)',
    plantToxicity: 'Non-toxic',
    plantPests: 'Cucumber beetles, aphids',
    plantDiseases: 'Powdery mildew, bacterial wilt',
    spacing: 12,
    growthType: PlantGrowthType.VERTICAL,
    isVerticalGrower: true
  },
  {
    plantName: 'Zucchini',
    plantType: 'Vegetable',
    plantVariety: '',
    plantImage: '/images/zucchini.png',
    plantWatering: 'Regular',
    plantLight: 'Full sun',
    plantSoil: 'Rich, well-draining',
    plantFertilizer: 'Balanced fertilizer',
    plantHumidity: 'Moderate',
    plantTemperature: '65-75°F (18-24°C)',
    plantToxicity: 'Non-toxic',
    plantPests: 'Squash bugs, squash vine borers',
    plantDiseases: 'Powdery mildew, blossom end rot',
    spacing: 18,
    growthType: PlantGrowthType.VERTICAL,
    isVerticalGrower: true
  },
  {
    plantName: 'Pumpkin',
    plantType: 'Vegetable',
    plantVariety: '',
    plantImage: '/images/pumpkin.png',
    plantWatering: 'Regular',
    plantLight: 'Full sun',
    plantSoil: 'Rich, well-draining soil',
    plantFertilizer: 'Balanced fertilizer',
    plantHumidity: 'Moderate',
    plantTemperature: '65-95°F (18-35°C)',
    plantToxicity: 'Non-toxic',
    plantPests: 'Squash bugs, cucumber beetles',
    plantDiseases: 'Powdery mildew, downy mildew',
    spacing: 36,
    growthType: PlantGrowthType.VERTICAL,
    isVerticalGrower: true
  },
  {
    plantName: 'Sunflower',
    plantType: 'Flower',
    plantVariety: '',
    plantImage: '/images/sunflower.png',
    plantWatering: 'Moderate',
    plantLight: 'Full sun',
    plantSoil: 'Well-draining, rich',
    plantFertilizer: 'Low nitrogen fertilizer',
    plantHumidity: 'Low to moderate',
    plantTemperature: '70-78°F (21-26°C)',
    plantToxicity: 'Non-toxic',
    plantPests: 'Aphids, beetles',
    plantDiseases: 'Rust, powdery mildew',
    spacing: 12,
    growthType: PlantGrowthType.NORMAL,
    isVerticalGrower: false
  },
  {
    plantName: 'Basil',
    plantType: 'Herb',
    plantVariety: '',
    plantImage: '/images/basil.png',
    plantWatering: 'Moderate',
    plantLight: 'Partial shade',
    plantSoil: 'Well-draining, rich in organic matter',
    plantFertilizer: 'Balanced, mild fertilizer',
    plantHumidity: 'Moderate',
    plantTemperature: '65-85°F (18-29°C)',
    plantToxicity: 'Non-toxic',
    plantPests: 'Aphids, slugs, Japanese beetles',
    plantDiseases: 'Downy mildew, fusarium wilt',
    spacing: 4,
    growthType: PlantGrowthType.NORMAL,
    isVerticalGrower: false
  },
  {
    plantName: 'Green Pepper',
    plantType: 'Vegetable',
    plantVariety: '',
    plantImage: '/images/pepper.png',
    plantWatering: 'Moderate',
    plantLight: 'Full sun',
    plantSoil: 'Well-draining, fertile soil',
    plantFertilizer: 'Balanced fertilizer',
    plantHumidity: 'Moderate',
    plantTemperature: '70-85°F (21-29°C)',
    plantToxicity: 'Non-toxic',
    plantPests: 'Aphids, spider mites, whiteflies',
    plantDiseases: 'Bacterial spot, powdery mildew',
    spacing: 12,
    growthType: PlantGrowthType.NORMAL,
    isVerticalGrower: false
  },
  {
    plantName: 'Broccoli',
    plantType: 'Vegetable',
    plantVariety: '',
    plantImage: '/images/broccoli.png',
    plantWatering: 'Regular',
    plantLight: 'Full sun',
    plantSoil: 'Rich, moist, well-draining',
    plantFertilizer: 'Nitrogen-rich fertilizer',
    plantHumidity: 'Moderate',
    plantTemperature: '60-70°F (15-21°C)',
    plantToxicity: 'Non-toxic',
    plantPests: 'Cabbage worms, aphids, flea beetles',
    plantDiseases: 'Black rot, downy mildew',
    spacing: 18,
    growthType: PlantGrowthType.NORMAL,
    isVerticalGrower: false
  },
  {
    plantName: 'Cauliflower',
    plantType: 'Vegetable',
    plantVariety: '',
    plantImage: '/images/cauliflower.png',
    plantWatering: 'Regular',
    plantLight: 'Full sun',
    plantSoil: 'Rich, well-draining soil',
    plantFertilizer: 'Balanced fertilizer',
    plantHumidity: 'Moderate',
    plantTemperature: '60-70°F (15-21°C)',
    plantToxicity: 'Non-toxic',
    plantPests: 'Cabbage worms, aphids, flea beetles',
    plantDiseases: 'Black rot, downy mildew',
    spacing: 18,
    growthType: PlantGrowthType.NORMAL,
    isVerticalGrower: false
  },
  {
    plantName: 'Onion',
    plantType: 'Vegetable',
    plantVariety: '',
    plantImage: '/images/onion.png',
    plantWatering: 'Moderate',
    plantLight: 'Full sun',
    plantSoil: 'Loose, well-draining soil',
    plantFertilizer: 'Nitrogen-rich at first, then phosphorus-rich',
    plantHumidity: 'Moderate',
    plantTemperature: '55-75°F (13-24°C)',
    plantToxicity: 'Toxic to cats and dogs',
    plantPests: 'Onion maggots, thrips',
    plantDiseases: 'Downy mildew, purple blotch',
    spacing: 4,
    growthType: PlantGrowthType.NORMAL,
    isVerticalGrower: false
  },
  {
    plantName: 'Garlic',
    plantType: 'Vegetable',
    plantVariety: '',
    plantImage: '/images/garlic.png',
    plantWatering: 'Low',
    plantLight: 'Full sun',
    plantSoil: 'Well-draining, rich soil',
    plantFertilizer: 'Balanced fertilizer',
    plantHumidity: 'Low to moderate',
    plantTemperature: '40-60°F (4-15°C)',
    plantToxicity: 'Toxic to cats and dogs',
    plantPests: 'Thrips, nematodes',
    plantDiseases: 'White rot, rust',
    spacing: 4,
    growthType: PlantGrowthType.NORMAL,
    isVerticalGrower: false
  },
  {
    plantName: 'Potato',
    plantType: 'Root vegetable',
    plantVariety: '',
    plantImage: '/images/potatoes.png',
    plantWatering: 'Moderate',
    plantLight: 'Full sun',
    plantSoil: 'Loose, well-draining soil',
    plantFertilizer: 'Balanced, low-nitrogen fertilizer',
    plantHumidity: 'Moderate',
    plantTemperature: '60-70°F (15-21°C)',
    plantToxicity: 'Green parts are toxic',
    plantPests: 'Colorado potato beetle, aphids',
    plantDiseases: 'Late blight, scab',
    spacing: 12,
    growthType: PlantGrowthType.NORMAL,
    isVerticalGrower: false
  },
  {
    plantName: 'Sweet Potato',
    plantType: 'Root vegetable',
    plantVariety: '',
    plantImage: '/images/sweet-potato.png',
    plantWatering: 'Moderate',
    plantLight: 'Full sun',
    plantSoil: 'Sandy, well-draining soil',
    plantFertilizer: 'Low-nitrogen fertilizer',
    plantHumidity: 'Moderate',
    plantTemperature: '75-85°F (24-29°C)',
    plantToxicity: 'Non-toxic',
    plantPests: 'Sweet potato weevils, wireworms',
    plantDiseases: 'Root rot, scurf',
    spacing: 12,
    growthType: PlantGrowthType.NORMAL,
    isVerticalGrower: false
  },
  {
    plantName: 'Corn',
    plantType: 'Grain',
    plantVariety: '',
    plantImage: '/images/corn.png',
    plantWatering: 'Regular',
    plantLight: 'Full sun',
    plantSoil: 'Rich, well-draining soil',
    plantFertilizer: 'Nitrogen-rich fertilizer',
    plantHumidity: 'Moderate',
    plantTemperature: '60-95°F (15-35°C)',
    plantToxicity: 'Non-toxic',
    plantPests: 'Corn earworms, corn borers',
    plantDiseases: 'Corn smut, leaf blight',
    spacing: 12,
    growthType: PlantGrowthType.NORMAL,
    isVerticalGrower: false
  },
  {
    plantName: 'Turnip',
    plantType: 'Root vegetable',
    plantVariety: '',
    plantImage: '/images/turnip.png',
    plantWatering: 'Regular',
    plantLight: 'Full sun',
    plantSoil: 'Loose, well-draining soil',
    plantFertilizer: 'Balanced fertilizer',
    plantHumidity: 'Moderate',
    plantTemperature: '55-75°F (13-24°C)',
    plantToxicity: 'Non-toxic',
    plantPests: 'Flea beetles, aphids',
    plantDiseases: 'Club root, black rot',
    spacing: 4,
    growthType: PlantGrowthType.NORMAL,
    isVerticalGrower: false
  },
  {
    plantName: 'Squash',
    plantType: 'Vegetable',
    plantVariety: '',
    plantImage: '/images/squash.png',
    plantWatering: 'Regular',
    plantLight: 'Full sun',
    plantSoil: 'Rich, well-draining soil',
    plantFertilizer: 'Balanced fertilizer',
    plantHumidity: 'Moderate',
    plantTemperature: '65-85°F (18-29°C)',
    plantToxicity: 'Non-toxic',
    plantPests: 'Squash bugs, cucumber beetles',
    plantDiseases: 'Powdery mildew, downy mildew',
    spacing: 24,
    growthType: PlantGrowthType.VERTICAL,
    isVerticalGrower: true
  },
  {
    plantName: 'Mint',
    plantType: 'Herb',
    plantVariety: '',
    plantImage: '/images/mint.png',
    plantWatering: 'Regular',
    plantLight: 'Partial shade',
    plantSoil: 'Rich, moist soil',
    plantFertilizer: 'Balanced fertilizer',
    plantHumidity: 'Moderate',
    plantTemperature: '55-70°F (13-21°C)',
    plantToxicity: 'Non-toxic',
    plantPests: 'Spider mites, aphids',
    plantDiseases: 'Rust, powdery mildew',
    spacing: 4,
    growthType: PlantGrowthType.NORMAL,
    isVerticalGrower: false
  },
  {
    plantName: 'Rosemary',
    plantType: 'Herb',
    plantVariety: '',
    plantImage: '/images/rosemary.png',
    plantWatering: 'Low',
    plantLight: 'Full sun',
    plantSoil: 'Well-draining, sandy soil',
    plantFertilizer: 'Low-nitrogen fertilizer',
    plantHumidity: 'Low',
    plantTemperature: '55-80°F (13-27°C)',
    plantToxicity: 'Non-toxic',
    plantPests: 'Spider mites, aphids',
    plantDiseases: 'Powdery mildew, root rot',
    spacing: 12,
    growthType: PlantGrowthType.NORMAL,
    isVerticalGrower: false
  },
  {
    plantName: 'Thyme',
    plantType: 'Herb',
    plantVariety: '',
    plantImage: '/images/thyme.png',
    plantWatering: 'Low',
    plantLight: 'Full sun',
    plantSoil: 'Well-draining, sandy soil',
    plantFertilizer: 'Balanced, mild fertilizer',
    plantHumidity: 'Low',
    plantTemperature: '50-80°F (10-27°C)',
    plantToxicity: 'Non-toxic',
    plantPests: 'Spider mites, aphids',
    plantDiseases: 'Root rot, botrytis',
    spacing: 6,
    growthType: PlantGrowthType.NORMAL,
    isVerticalGrower: false
  },
  {
    plantName: 'Cherry Tomato',
    plantType: 'Vegetable',
    plantVariety: '',
    plantImage: '/images/cherry-tomato.png',
    plantWatering: 'Regular',
    plantLight: 'Full sun',
    plantSoil: 'Rich, well-draining soil',
    plantFertilizer: 'Balanced fertilizer',
    plantHumidity: 'Moderate',
    plantTemperature: '65-85°F (18-29°C)',
    plantToxicity: 'Leaves and stems are toxic to pets',
    plantPests: 'Aphids, hornworms, whiteflies',
    plantDiseases: 'Blight, wilt, powdery mildew',
    spacing: 12,
    growthType: PlantGrowthType.VERTICAL,
    isVerticalGrower: true
  },
  {
    plantName: 'Asparagus',
    plantType: 'Vegetable',
    plantVariety: '',
    plantImage: '/images/asparagus.png',
    plantWatering: 'Moderate',
    plantLight: 'Full sun',
    plantSoil: 'Well-draining, sandy soil',
    plantFertilizer: 'Balanced fertilizer',
    plantHumidity: 'Moderate',
    plantTemperature: '65-85°F (18-29°C)',
    plantToxicity: 'Non-toxic',
    plantPests: 'Asparagus beetles, aphids',
    plantDiseases: 'Rust, fusarium crown rot',
    spacing: 12,
    growthType: PlantGrowthType.NORMAL,
    isVerticalGrower: false
  },
  {
    plantName: 'Beet',
    plantType: 'Root vegetable',
    plantVariety: '',
    plantImage: '/images/beet.png',
    plantWatering: 'Moderate',
    plantLight: 'Full sun',
    plantSoil: 'Loose, well-draining soil',
    plantFertilizer: 'Balanced fertilizer',
    plantHumidity: 'Moderate',
    plantTemperature: '50-75°F (10-24°C)',
    plantToxicity: 'Non-toxic',
    plantPests: 'Leaf miners, aphids',
    plantDiseases: 'Leaf spot, downy mildew',
    spacing: 4,
    growthType: PlantGrowthType.NORMAL,
    isVerticalGrower: false
  },
  {
    plantName: 'Red Pepper',
    plantType: 'Vegetable',
    plantVariety: '',
    plantImage: '/images/red-pepper.png',
    plantWatering: 'Moderate',
    plantLight: 'Full sun',
    plantSoil: 'Rich, well-draining soil',
    plantFertilizer: 'Balanced fertilizer',
    plantHumidity: 'Moderate',
    plantTemperature: '70-85°F (21-29°C)',
    plantToxicity: 'Non-toxic',
    plantPests: 'Aphids, spider mites',
    plantDiseases: 'Bacterial spot, blossom end rot',
    spacing: 12,
    growthType: PlantGrowthType.NORMAL,
    isVerticalGrower: false
  },
  {
    plantName: 'Celery',
    plantType: 'Vegetable',
    plantVariety: '',
    plantImage: '/images/celery.png',
    plantWatering: 'Regular',
    plantLight: 'Partial shade',
    plantSoil: 'Rich, moist soil',
    plantFertilizer: 'Balanced fertilizer',
    plantHumidity: 'High',
    plantTemperature: '60-70°F (15-21°C)',
    plantToxicity: 'Non-toxic',
    plantPests: 'Aphids, slugs',
    plantDiseases: 'Early blight, pink rot',
    spacing: 6,
    growthType: PlantGrowthType.NORMAL,
    isVerticalGrower: false
  },
  {
    plantName: 'Cabbage',
    plantType: 'Vegetable',
    plantVariety: '',
    plantImage: '/images/cabbage.png',
    plantWatering: 'Regular',
    plantLight: 'Full sun',
    plantSoil: 'Rich, well-draining soil',
    plantFertilizer: 'Balanced fertilizer',
    plantHumidity: 'Moderate',
    plantTemperature: '60-70°F (15-21°C)',
    plantToxicity: 'Non-toxic',
    plantPests: 'Cabbage worms, aphids, flea beetles',
    plantDiseases: 'Black rot, clubroot',
    spacing: 12,
    growthType: PlantGrowthType.NORMAL,
    isVerticalGrower: false
  },
  {
    plantName: 'Eggplant',
    plantType: 'Vegetable',
    plantVariety: '',
    plantImage: '/images/eggplant.png',
    plantWatering: 'Regular',
    plantLight: 'Full sun',
    plantSoil: 'Rich, well-draining soil',
    plantFertilizer: 'Balanced fertilizer',
    plantHumidity: 'Moderate',
    plantTemperature: '70-85°F (21-29°C)',
    plantToxicity: 'Non-toxic',
    plantPests: 'Flea beetles, spider mites',
    plantDiseases: 'Verticillium wilt, blossom end rot',
    spacing: 18,
    growthType: PlantGrowthType.NORMAL,
    isVerticalGrower: false
  },
  {
    plantName: 'Kale',
    plantType: 'Leafy green',
    plantVariety: '',
    plantImage: '/images/kale.png',
    plantWatering: 'Regular',
    plantLight: 'Full sun',
    plantSoil: 'Rich, well-draining soil',
    plantFertilizer: 'Nitrogen-rich fertilizer',
    plantHumidity: 'Moderate',
    plantTemperature: '55-75°F (13-24°C)',
    plantToxicity: 'Non-toxic',
    plantPests: 'Aphids, cabbage worms',
    plantDiseases: 'Downy mildew, powdery mildew',
    spacing: 12,
    growthType: PlantGrowthType.NORMAL,
    isVerticalGrower: false
  },
  {
    plantName: 'Spinach',
    plantType: 'Leafy green',
    plantVariety: '',
    plantImage: '/images/spinach.png',
    plantWatering: 'Regular',
    plantLight: 'Partial shade',
    plantSoil: 'Rich, well-draining soil',
    plantFertilizer: 'Nitrogen-rich fertilizer',
    plantHumidity: 'Moderate',
    plantTemperature: '50-70°F (10-21°C)',
    plantToxicity: 'Non-toxic',
    plantPests: 'Aphids, leaf miners',
    plantDiseases: 'Downy mildew, leaf spot',
    spacing: 3,
    growthType: PlantGrowthType.NORMAL,
    isVerticalGrower: false
  },
  {
    plantName: 'Strawberry',
    plantType: 'Fruit',
    plantVariety: '',
    plantImage: '/images/strawberry.png',
    plantWatering: 'Regular',
    plantLight: 'Full sun',
    plantSoil: 'Rich, well-draining soil',
    plantFertilizer: 'Balanced fertilizer',
    plantHumidity: 'Moderate',
    plantTemperature: '60-80°F (15-27°C)',
    plantToxicity: 'Non-toxic',
    plantPests: 'Slugs, aphids, spider mites',
    plantDiseases: 'Gray mold, leaf spot',
    spacing: 6,
    growthType: PlantGrowthType.NORMAL,
    isVerticalGrower: false
  },
  {
    plantName: 'Blueberry',
    plantType: 'Fruit',
    plantVariety: '',
    plantImage: '/images/blueberry.png',
    plantWatering: 'Regular',
    plantLight: 'Full sun',
    plantSoil: 'Acidic, well-draining soil',
    plantFertilizer: 'Acidic fertilizer',
    plantHumidity: 'Moderate',
    plantTemperature: '60-80°F (15-27°C)',
    plantToxicity: 'Non-toxic',
    plantPests: 'Blueberry maggots, aphids',
    plantDiseases: 'Mummy berry, powdery mildew',
    spacing: 18,
    growthType: PlantGrowthType.NORMAL,
    isVerticalGrower: false
  },
  {
    plantName: 'Raspberry',
    plantType: 'Fruit',
    plantVariety: '',
    plantImage: '/images/raspberry.png',
    plantWatering: 'Regular',
    plantLight: 'Full sun',
    plantSoil: 'Rich, well-draining soil',
    plantFertilizer: 'Balanced fertilizer',
    plantHumidity: 'Moderate',
    plantTemperature: '60-80°F (15-27°C)',
    plantToxicity: 'Non-toxic',
    plantPests: 'Japanese beetles, aphids',
    plantDiseases: 'Gray mold, cane blight',
    spacing: 18,
    growthType: PlantGrowthType.NORMAL,
    isVerticalGrower: false
  },
  {
    plantName: 'Watermelon',
    plantType: 'Fruit',
    plantVariety: '',
    plantImage: '/images/watermelon.png',
    plantWatering: 'Regular',
    plantLight: 'Full sun',
    plantSoil: 'Sandy, well-draining soil',
    plantFertilizer: 'Balanced fertilizer',
    plantHumidity: 'Moderate',
    plantTemperature: '70-90°F (21-32°C)',
    plantToxicity: 'Non-toxic',
    plantPests: 'Cucumber beetles, aphids',
    plantDiseases: 'Powdery mildew, fusarium wilt',
    spacing: 36,
    growthType: PlantGrowthType.VERTICAL,
    isVerticalGrower: true
  },
  {
    plantName: 'Cantaloupe',
    plantType: 'Fruit',
    plantVariety: '',
    plantImage: '/images/cantaloupe.png',
    plantWatering: 'Regular',
    plantLight: 'Full sun',
    plantSoil: 'Sandy, well-draining soil',
    plantFertilizer: 'Balanced fertilizer',
    plantHumidity: 'Moderate',
    plantTemperature: '70-90°F (21-32°C)',
    plantToxicity: 'Non-toxic',
    plantPests: 'Cucumber beetles, aphids',
    plantDiseases: 'Powdery mildew, downy mildew',
    spacing: 36,
    growthType: PlantGrowthType.VERTICAL,
    isVerticalGrower: true
  },
  {
    plantName: 'Radish',
    plantType: 'Root vegetable',
    plantVariety: '',
    plantImage: '/images/radish.png',
    plantWatering: 'Regular',
    plantLight: 'Full sun',
    plantSoil: 'Loose, well-draining soil',
    plantFertilizer: 'Balanced fertilizer',
    plantHumidity: 'Moderate',
    plantTemperature: '55-75°F (13-24°C)',
    plantToxicity: 'Non-toxic',
    plantPests: 'Flea beetles, root maggots',
    plantDiseases: 'Downy mildew, black root',
    spacing: 3,
    growthType: PlantGrowthType.NORMAL,
    isVerticalGrower: false
  },
  {
    plantName: 'Peas',
    plantType: 'Vegetable',
    plantVariety: '',
    plantImage: '/images/peas.png',
    plantWatering: 'Moderate',
    plantLight: 'Full sun',
    plantSoil: 'Rich, well-draining soil',
    plantFertilizer: 'Low-nitrogen fertilizer',
    plantHumidity: 'Moderate',
    plantTemperature: '55-70°F (13-21°C)',
    plantToxicity: 'Non-toxic',
    plantPests: 'Aphids, pea moths',
    plantDiseases: 'Powdery mildew, root rot',
    spacing: 4,
    growthType: PlantGrowthType.VERTICAL_BEAN_PEA,
    isVerticalGrower: true
  },
  {
    plantName: 'Beans',
    plantType: 'Vegetable',
    plantVariety: '',
    plantImage: '/images/red-beans.png',
    plantWatering: 'Moderate',
    plantLight: 'Full sun',
    plantSoil: 'Well-draining, moderately rich soil',
    plantFertilizer: 'Low-nitrogen fertilizer',
    plantHumidity: 'Moderate',
    plantTemperature: '65-85°F (18-29°C)',
    plantToxicity: 'Some varieties have toxic raw beans',
    plantPests: 'Bean beetles, aphids',
    plantDiseases: 'Bacterial blight, rust',
    spacing: 4,
    growthType: PlantGrowthType.VERTICAL_BEAN_PEA,
    isVerticalGrower: true
  },
  {
    plantName: 'Okra',
    plantType: 'Vegetable',
    plantVariety: '',
    plantImage: '/images/okra.png',
    plantWatering: 'Regular',
    plantLight: 'Full sun',
    plantSoil: 'Rich, well-draining soil',
    plantFertilizer: 'Balanced fertilizer',
    plantHumidity: 'Moderate to high',
    plantTemperature: '70-95°F (21-35°C)',
    plantToxicity: 'Non-toxic',
    plantPests: 'Aphids, stink bugs',
    plantDiseases: 'Powdery mildew, leaf spot',
    spacing: 12,
    growthType: PlantGrowthType.NORMAL,
    isVerticalGrower: false
  },
  {
    plantName: 'Brussels Sprouts',
    plantType: 'Vegetable',
    plantVariety: '',
    plantImage: '/images/brussels-sprouts.png',
    plantWatering: 'Regular',
    plantLight: 'Full sun',
    plantSoil: 'Rich, well-draining soil',
    plantFertilizer: 'Nitrogen-rich fertilizer',
    plantHumidity: 'Moderate',
    plantTemperature: '45-75°F (7-24°C)',
    plantToxicity: 'Non-toxic',
    plantPests: 'Aphids, cabbage worms',
    plantDiseases: 'Black rot, clubroot',
    spacing: 18,
    growthType: PlantGrowthType.NORMAL,
    isVerticalGrower: false
  },
  {
    plantName: 'Artichoke',
    plantType: 'Vegetable',
    plantVariety: '',
    plantImage: '/images/artichoke.png',
    plantWatering: 'Regular',
    plantLight: 'Full sun',
    plantSoil: 'Rich, well-draining soil',
    plantFertilizer: 'Balanced fertilizer',
    plantHumidity: 'Moderate',
    plantTemperature: '55-75°F (13-24°C)',
    plantToxicity: 'Non-toxic',
    plantPests: 'Aphids, slugs',
    plantDiseases: 'Powdery mildew, botrytis',
    spacing: 36,
    growthType: PlantGrowthType.NORMAL,
    isVerticalGrower: false
  },
  {
    plantName: 'Yellow Pepper',
    plantType: 'Vegetable',
    plantVariety: '',
    plantImage: '/images/yellow-pepper.png',
    plantWatering: 'Moderate',
    plantLight: 'Full sun',
    plantSoil: 'Rich, well-draining soil',
    plantFertilizer: 'Balanced fertilizer',
    plantHumidity: 'Moderate',
    plantTemperature: '70-85°F (21-29°C)',
    plantToxicity: 'Non-toxic',
    plantPests: 'Aphids, spider mites',
    plantDiseases: 'Bacterial spot, blossom end rot',
    spacing: 12,
    growthType: PlantGrowthType.NORMAL,
    isVerticalGrower: false
  },
  {
    plantName: 'Chili Pepper',
    plantType: 'Vegetable',
    plantVariety: '',
    plantImage: '/images/chili-pepper.png',
    plantWatering: 'Moderate',
    plantLight: 'Full sun',
    plantSoil: 'Rich, well-draining soil',
    plantFertilizer: 'Balanced fertilizer',
    plantHumidity: 'Moderate',
    plantTemperature: '70-85°F (21-29°C)',
    plantToxicity: 'Non-toxic',
    plantPests: 'Aphids, spider mites',
    plantDiseases: 'Bacterial spot, blossom end rot',
    spacing: 12,
    growthType: PlantGrowthType.NORMAL,
    isVerticalGrower: false
  }
];

const seedDB = async () => {
  if (process.env.SEED_DATABASE === 'true') {
    try {
      // Connect to the database
      await db();
      console.log('Connected to the database');
      
      // Clear existing collections
      await cleanDB();
      console.log('Database cleared');
      
      // Seed plants
      await Plant.insertMany(plantSeeds);
      console.log(`${plantSeeds.length} plants inserted into database`);
      
      console.log('Database seeding completed successfully!');
      process.exit(0);
    
    } catch (err) {
      console.error('Error seeding database:', err);
      process.exit(1);
    }
  } else {
    console.log('Seeding skipped. Set SEED_DATABASE=true to seed the database.');
    process.exit(0);
  }
};

seedDB();