import Plant from '../models/Plant.js';
import db from '../config/connection.js';
import cleanDB from './cleanDB.js';


// Plant data from the client-side plantData.ts file, adapted for the database
const plantSeeds = [
  {
    plantName: 'Tomato',
    plantType: 'Vegetable',
    plantDescription: 'A popular garden vegetable that produces red, juicy fruits.',
    plantImage: '/images/tomato.png',
    plantWatering: 'Regular',
    plantLight: 'Full sun',
    plantSoil: 'Well-draining, rich in organic matter',
    plantFertilizer: 'Balanced fertilizer, higher in phosphorus when fruiting',
    plantHumidity: 'Moderate',
    plantTemperature: '65-85°F (18-29°C)',
    plantToxicity: 'Leaves and stems are toxic to pets',
    plantPests: 'Aphids, hornworms, whiteflies',
    plantDiseases: 'Blight, wilt, powdery mildew',
    spacing: 18,
    plantsPerSquareFoot: 0.25,
    color: '#e77c7c',
  },
  {
    plantName: 'Carrot',
    plantType: 'Root vegetable',
    plantDescription: 'A root vegetable known for its orange color and sweet taste.',
    plantImage: '/images/carrot.png',
    plantWatering: 'Moderate',
    plantLight: 'Full sun',
    plantSoil: 'Loose, sandy, well-draining',
    plantFertilizer: 'Low nitrogen, high potassium',
    plantHumidity: 'Moderate',
    plantTemperature: '60-70°F (15-21°C)',
    plantToxicity: 'Non-toxic',
    plantPests: 'Carrot rust flies, nematodes',
    plantDiseases: 'Leaf blight, powdery mildew',
    spacing: 3,
    plantsPerSquareFoot: 16,
    color: '#e9a978',
  },
  {
    plantName: 'Lettuce',
    plantType: 'Leafy green',
    plantDescription: 'A leafy vegetable often used in salads and sandwiches.',
    plantImage: '/images/lettuce.png',
    plantWatering: 'Regular',
    plantLight: 'Partial shade',
    plantSoil: 'Rich, moist, well-draining',
    plantFertilizer: 'Nitrogen-rich fertilizer',
    plantHumidity: 'Moderate',
    plantTemperature: '45-75°F (7-24°C)',
    plantToxicity: 'Non-toxic',
    plantPests: 'Aphids, slugs, snails',
    plantDiseases: 'Downy mildew, bottom rot',
    spacing: 6,
    plantsPerSquareFoot: 4,
    color: '#8dd8b9',
  },
  {
    plantName: 'Cucumber',
    plantType: 'Vegetable',
    plantDescription: 'A climbing vine that produces crisp, refreshing fruits.',
    plantImage: '/images/cucumber.png',
    plantWatering: 'Regular',
    plantLight: 'Full sun',
    plantSoil: 'Rich, well-draining',
    plantFertilizer: 'Balanced fertilizer',
    plantHumidity: 'Moderate to high',
    plantTemperature: '65-85°F (18-29°C)',
    plantToxicity: 'Non-toxic',
    plantPests: 'Cucumber beetles, aphids',
    plantDiseases: 'Powdery mildew, bacterial wilt',
    spacing: 12,
    plantsPerSquareFoot: 1,
    color: '#78c2a4',
  },
  {
    plantName: 'Zucchini',
    plantType: 'Vegetable',
    plantDescription: 'A summer squash with dark green skin and white flesh.',
    plantImage: '/images/zucchini.png',
    plantWatering: 'Regular',
    plantLight: 'Full sun',
    plantSoil: 'Rich, well-draining',
    plantFertilizer: 'Balanced fertilizer',
    plantHumidity: 'Moderate',
    plantTemperature: '65-75°F (18-24°C)',
    plantToxicity: 'Non-toxic',
    plantPests: 'Squash bugs, squash vine borers',
    plantDiseases: 'Powdery mildew, blossom end rot',
    spacing: 18,
    plantsPerSquareFoot: 0.25,
    color: '#7fb3da',
  },
  {
    plantName: 'Pumpkin',
    plantType: 'Vegetable',
    plantDescription: 'A large, orange winter squash used for cooking and decoration.',
    plantImage: '/images/pumpkin.png',
    plantWatering: 'Regular',
    plantLight: 'Full sun',
    plantSoil: 'Rich, well-draining soil',
    plantFertilizer: 'Balanced fertilizer',
    plantHumidity: 'Moderate',
    plantTemperature: '65-95°F (18-35°C)',
    plantToxicity: 'Non-toxic',
    plantPests: 'Squash bugs, cucumber beetles',
    plantDiseases: 'Powdery mildew, downy mildew',
    spacing: 36,
    plantsPerSquareFoot: 0.25,
    color: '#e2a173',
  },
  {
    plantName: 'Sunflower',
    plantType: 'Flower',
    plantDescription: 'A tall annual with bright yellow flowers that follow the sun.',
    plantImage: '/images/sunflower.png',
    plantWatering: 'Moderate',
    plantLight: 'Full sun',
    plantSoil: 'Well-draining, rich',
    plantFertilizer: 'Low nitrogen fertilizer',
    plantHumidity: 'Low to moderate',
    plantTemperature: '70-78°F (21-26°C)',
    plantToxicity: 'Non-toxic',
    plantPests: 'Aphids, beetles',
    plantDiseases: 'Rust, powdery mildew',
    spacing: 12,
    plantsPerSquareFoot: 1,
    color: '#ecd279',
  },
  {
    plantName: 'Basil',
    plantType: 'Herb',
    plantDescription: 'An aromatic herb with tender green leaves used in many cuisines.',
    plantImage: '/images/basil.png',
    plantWatering: 'Moderate',
    plantLight: 'Partial shade',
    plantSoil: 'Well-draining, rich in organic matter',
    plantFertilizer: 'Balanced, mild fertilizer',
    plantHumidity: 'Moderate',
    plantTemperature: '65-85°F (18-29°C)',
    plantToxicity: 'Non-toxic',
    plantPests: 'Aphids, slugs, Japanese beetles',
    plantDiseases: 'Downy mildew, fusarium wilt',
    spacing: 4,
    plantsPerSquareFoot: 9,
    color: '#97c283',
  },
  {
    plantName: 'Pepper',
    plantType: 'Vegetable',
    plantDescription: 'A versatile vegetable that ranges from sweet to spicy varieties.',
    plantImage: '/images/pepper.png',
    plantWatering: 'Moderate',
    plantLight: 'Full sun',
    plantSoil: 'Well-draining, fertile soil',
    plantFertilizer: 'Balanced fertilizer',
    plantHumidity: 'Moderate',
    plantTemperature: '70-85°F (21-29°C)',
    plantToxicity: 'Non-toxic',
    plantPests: 'Aphids, spider mites, whiteflies',
    plantDiseases: 'Bacterial spot, powdery mildew',
    spacing: 12,
    plantsPerSquareFoot: 1,
    color: '#e28b89',
  },
  {
    plantName: 'Broccoli',
    plantType: 'Vegetable',
    plantDescription: 'A nutritious cruciferous vegetable with dense green heads.',
    plantImage: '/images/broccoli.png',
    plantWatering: 'Regular',
    plantLight: 'Full sun',
    plantSoil: 'Rich, moist, well-draining',
    plantFertilizer: 'Nitrogen-rich fertilizer',
    plantHumidity: 'Moderate',
    plantTemperature: '60-70°F (15-21°C)',
    plantToxicity: 'Non-toxic',
    plantPests: 'Cabbage worms, aphids, flea beetles',
    plantDiseases: 'Black rot, downy mildew',
    spacing: 18,
    plantsPerSquareFoot: 0.25,
    color: '#89bb9e',
  },
  {
    plantName: 'Cauliflower',
    plantType: 'Vegetable',
    plantDescription: 'A cruciferous vegetable with white, compact heads.',
    plantImage: '/images/cauliflower.png',
    plantWatering: 'Regular',
    plantLight: 'Full sun',
    plantSoil: 'Rich, well-draining soil',
    plantFertilizer: 'Balanced fertilizer',
    plantHumidity: 'Moderate',
    plantTemperature: '60-70°F (15-21°C)',
    plantToxicity: 'Non-toxic',
    plantPests: 'Cabbage worms, aphids, flea beetles',
    plantDiseases: 'Black rot, downy mildew',
    spacing: 18,
    plantsPerSquareFoot: 0.25,
    color: '#e0e0e0',
  },
  {
    plantName: 'Onion',
    plantType: 'Vegetable',
    plantDescription: 'A root vegetable with layered bulbs and distinctive flavor.',
    plantImage: '/images/onion.png',
    plantWatering: 'Moderate',
    plantLight: 'Full sun',
    plantSoil: 'Loose, well-draining soil',
    plantFertilizer: 'Nitrogen-rich at first, then phosphorus-rich',
    plantHumidity: 'Moderate',
    plantTemperature: '55-75°F (13-24°C)',
    plantToxicity: 'Toxic to cats and dogs',
    plantPests: 'Onion maggots, thrips',
    plantDiseases: 'Downy mildew, purple blotch',
    spacing: 4,
    plantsPerSquareFoot: 9,
    color: '#b8c4d0',
  },
  {
    plantName: 'Garlic',
    plantType: 'Vegetable',
    plantDescription: 'A bulbous plant with strong flavor, used in many cuisines.',
    plantImage: '/images/garlic.png',
    plantWatering: 'Low',
    plantLight: 'Full sun',
    plantSoil: 'Well-draining, rich soil',
    plantFertilizer: 'Balanced fertilizer',
    plantHumidity: 'Low to moderate',
    plantTemperature: '40-60°F (4-15°C)',
    plantToxicity: 'Toxic to cats and dogs',
    plantPests: 'Thrips, nematodes',
    plantDiseases: 'White rot, rust',
    spacing: 4,
    plantsPerSquareFoot: 9,
    color: '#d5d8dd',
  },
  {
    plantName: 'Potato',
    plantType: 'Root vegetable',
    plantDescription: 'A starchy tuber crop that grows underground.',
    plantImage: '/images/potatoes.png',
    plantWatering: 'Moderate',
    plantLight: 'Full sun',
    plantSoil: 'Loose, well-draining soil',
    plantFertilizer: 'Balanced, low-nitrogen fertilizer',
    plantHumidity: 'Moderate',
    plantTemperature: '60-70°F (15-21°C)',
    plantToxicity: 'Green parts are toxic',
    plantPests: 'Colorado potato beetle, aphids',
    plantDiseases: 'Late blight, scab',
    spacing: 12,
    plantsPerSquareFoot: 1,
    color: '#c4b396',
  },
  {
    plantName: 'Sweet Potato',
    plantType: 'Root vegetable',
    plantDescription: 'A sweet, starchy root vegetable with colorful flesh.',
    plantImage: '/images/sweet-potato.png',
    plantWatering: 'Moderate',
    plantLight: 'Full sun',
    plantSoil: 'Sandy, well-draining soil',
    plantFertilizer: 'Low-nitrogen fertilizer',
    plantHumidity: 'Moderate',
    plantTemperature: '75-85°F (24-29°C)',
    plantToxicity: 'Non-toxic',
    plantPests: 'Sweet potato weevils, wireworms',
    plantDiseases: 'Root rot, scurf',
    spacing: 12,
    plantsPerSquareFoot: 1,
    color: '#d49c82',
  },
  {
    plantName: 'Corn',
    plantType: 'Grain',
    plantDescription: 'A tall cereal grain that produces ears with kernels.',
    plantImage: '/images/corn.png',
    plantWatering: 'Regular',
    plantLight: 'Full sun',
    plantSoil: 'Rich, well-draining soil',
    plantFertilizer: 'Nitrogen-rich fertilizer',
    plantHumidity: 'Moderate',
    plantTemperature: '60-95°F (15-35°C)',
    plantToxicity: 'Non-toxic',
    plantPests: 'Corn earworms, corn borers',
    plantDiseases: 'Corn smut, leaf blight',
    spacing: 12,
    plantsPerSquareFoot: 1,
    color: '#e6d7a1',
  },
  {
    plantName: 'Turnip',
    plantType: 'Root vegetable',
    plantDescription: 'A root vegetable with white flesh and mild flavor.',
    plantImage: '/images/turnip.png',
    plantWatering: 'Regular',
    plantLight: 'Full sun',
    plantSoil: 'Loose, well-draining soil',
    plantFertilizer: 'Balanced fertilizer',
    plantHumidity: 'Moderate',
    plantTemperature: '55-75°F (13-24°C)',
    plantToxicity: 'Non-toxic',
    plantPests: 'Flea beetles, aphids',
    plantDiseases: 'Club root, black rot',
    spacing: 4,
    plantsPerSquareFoot: 9,
    color: '#ccd5ae',
  },
  {
    plantName: 'Squash',
    plantType: 'Vegetable',
    plantDescription: 'A diverse group of vegetables with edible flesh and seeds.',
    plantImage: '/images/squash.png',
    plantWatering: 'Regular',
    plantLight: 'Full sun',
    plantSoil: 'Rich, well-draining soil',
    plantFertilizer: 'Balanced fertilizer',
    plantHumidity: 'Moderate',
    plantTemperature: '65-85°F (18-29°C)',
    plantToxicity: 'Non-toxic',
    plantPests: 'Squash bugs, cucumber beetles',
    plantDiseases: 'Powdery mildew, downy mildew',
    spacing: 24,
    plantsPerSquareFoot: 0.25,
    color: '#ffc300',
  },
  {
    plantName: 'Mint',
    plantType: 'Herb',
    plantDescription: 'An aromatic herb with refreshing flavor and spreading growth habit.',
    plantImage: '/images/mint.png',
    plantWatering: 'Regular',
    plantLight: 'Partial shade',
    plantSoil: 'Rich, moist soil',
    plantFertilizer: 'Balanced fertilizer',
    plantHumidity: 'Moderate',
    plantTemperature: '55-70°F (13-21°C)',
    plantToxicity: 'Non-toxic',
    plantPests: 'Spider mites, aphids',
    plantDiseases: 'Rust, powdery mildew',
    spacing: 4,
    plantsPerSquareFoot: 9,
    color: '#2a9d8f',
  },
  {
    plantName: 'Rosemary',
    plantType: 'Herb',
    plantDescription: 'A woody, perennial herb with fragrant, needle-like leaves.',
    plantImage: '/images/rosemary.png',
    plantWatering: 'Low',
    plantLight: 'Full sun',
    plantSoil: 'Well-draining, sandy soil',
    plantFertilizer: 'Low-nitrogen fertilizer',
    plantHumidity: 'Low',
    plantTemperature: '55-80°F (13-27°C)',
    plantToxicity: 'Non-toxic',
    plantPests: 'Spider mites, aphids',
    plantDiseases: 'Powdery mildew, root rot',
    spacing: 12,
    plantsPerSquareFoot: 1,
    color: '#386641',
  },
  {
    plantName: 'Thyme',
    plantType: 'Herb',
    plantDescription: 'A low-growing, woody herb with small, aromatic leaves.',
    plantImage: '/images/thyme.png',
    plantWatering: 'Low',
    plantLight: 'Full sun',
    plantSoil: 'Well-draining, sandy soil',
    plantFertilizer: 'Balanced, mild fertilizer',
    plantHumidity: 'Low',
    plantTemperature: '50-80°F (10-27°C)',
    plantToxicity: 'Non-toxic',
    plantPests: 'Spider mites, aphids',
    plantDiseases: 'Root rot, botrytis',
    spacing: 6,
    plantsPerSquareFoot: 4,
    color: '#606c38',
  },
  {
    plantName: 'Cherry Tomato',
    plantType: 'Vegetable',
    plantDescription: 'A small, sweet variety of tomato that grows in clusters.',
    plantImage: '/images/cherry-tomato.png',
    plantWatering: 'Regular',
    plantLight: 'Full sun',
    plantSoil: 'Rich, well-draining soil',
    plantFertilizer: 'Balanced fertilizer',
    plantHumidity: 'Moderate',
    plantTemperature: '65-85°F (18-29°C)',
    plantToxicity: 'Leaves and stems are toxic to pets',
    plantPests: 'Aphids, hornworms, whiteflies',
    plantDiseases: 'Blight, wilt, powdery mildew',
    spacing: 12,
    plantsPerSquareFoot: 1,
    color: '#e63946',
  },
  {
    plantName: 'Asparagus',
    plantType: 'Vegetable',
    plantDescription: 'A perennial vegetable that produces tender, edible stalks.',
    plantImage: '/images/asparagus.png',
    plantWatering: 'Moderate',
    plantLight: 'Full sun',
    plantSoil: 'Well-draining, sandy soil',
    plantFertilizer: 'Balanced fertilizer',
    plantHumidity: 'Moderate',
    plantTemperature: '65-85°F (18-29°C)',
    plantToxicity: 'Non-toxic',
    plantPests: 'Asparagus beetles, aphids',
    plantDiseases: 'Rust, fusarium crown rot',
    spacing: 12,
    plantsPerSquareFoot: 1,
    color: '#8dbd8a',
  },
  {
    plantName: 'Beet',
    plantType: 'Root vegetable',
    plantDescription: 'A colorful root vegetable with edible tops.',
    plantImage: '/images/beet.png',
    plantWatering: 'Moderate',
    plantLight: 'Full sun',
    plantSoil: 'Loose, well-draining soil',
    plantFertilizer: 'Balanced fertilizer',
    plantHumidity: 'Moderate',
    plantTemperature: '50-75°F (10-24°C)',
    plantToxicity: 'Non-toxic',
    plantPests: 'Leaf miners, aphids',
    plantDiseases: 'Leaf spot, downy mildew',
    spacing: 4,
    plantsPerSquareFoot: 9,
    color: '#8a284c',
  },
  {
    plantName: 'Bell Pepper',
    plantType: 'Vegetable',
    plantDescription: 'A sweet, crunchy vegetable available in various colors.',
    plantImage: '/images/bell-pepper.png',
    plantWatering: 'Moderate',
    plantLight: 'Full sun',
    plantSoil: 'Rich, well-draining soil',
    plantFertilizer: 'Balanced fertilizer',
    plantHumidity: 'Moderate',
    plantTemperature: '70-85°F (21-29°C)',
    plantToxicity: 'Non-toxic',
    plantPests: 'Aphids, spider mites',
    plantDiseases: 'Bacterial spot, blossom end rot',
    spacing: 12,
    plantsPerSquareFoot: 1,
    color: '#c82333',
  },
  {
    plantName: 'Celery',
    plantType: 'Vegetable',
    plantDescription: 'A crisp vegetable with long, fibrous stalks.',
    plantImage: '/images/celery.png',
    plantWatering: 'Regular',
    plantLight: 'Partial shade',
    plantSoil: 'Rich, moist soil',
    plantFertilizer: 'Balanced fertilizer',
    plantHumidity: 'High',
    plantTemperature: '60-70°F (15-21°C)',
    plantToxicity: 'Non-toxic',
    plantPests: 'Aphids, slugs',
    plantDiseases: 'Early blight, pink rot',
    spacing: 6,
    plantsPerSquareFoot: 4,
    color: '#a5cd9f',
  },

  {
    plantName: 'Cabbage',
    plantType: 'Vegetable',
    plantDescription: 'A leafy vegetable with tightly packed leaves forming a head.',
    plantImage: '/images/cabbage.png',
    plantWatering: 'Regular',
    plantLight: 'Full sun',
    plantSoil: 'Rich, well-draining soil',
    plantFertilizer: 'Balanced fertilizer',
    plantHumidity: 'Moderate',
    plantTemperature: '60-70°F (15-21°C)',
    plantToxicity: 'Non-toxic',
    plantPests: 'Cabbage worms, aphids, flea beetles',
    plantDiseases: 'Black rot, clubroot',
    spacing: 12,
    plantsPerSquareFoot: 1,
    color: '#adcfa8',
  },
  {
    plantName: 'Eggplant',
    plantType: 'Vegetable',
    plantDescription: 'A vegetable with glossy purple skin and spongy flesh.',
    plantImage: '/images/eggplant.png',
    plantWatering: 'Regular',
    plantLight: 'Full sun',
    plantSoil: 'Rich, well-draining soil',
    plantFertilizer: 'Balanced fertilizer',
    plantHumidity: 'Moderate',
    plantTemperature: '70-85°F (21-29°C)',
    plantToxicity: 'Non-toxic',
    plantPests: 'Flea beetles, spider mites',
    plantDiseases: 'Verticillium wilt, blossom end rot',
    spacing: 18,
    plantsPerSquareFoot: 0.25,
    color: '#614051',
  },
  {
    plantName: 'Kale',
    plantType: 'Leafy green',
    plantDescription: 'A nutritious leafy green with curly or flat leaves.',
    plantImage: '/images/kale.png',
    plantWatering: 'Regular',
    plantLight: 'Full sun',
    plantSoil: 'Rich, well-draining soil',
    plantFertilizer: 'Nitrogen-rich fertilizer',
    plantHumidity: 'Moderate',
    plantTemperature: '55-75°F (13-24°C)',
    plantToxicity: 'Non-toxic',
    plantPests: 'Aphids, cabbage worms',
    plantDiseases: 'Downy mildew, powdery mildew',
    spacing: 12,
    plantsPerSquareFoot: 1,
    color: '#3a5f0b',
  },
  {
    plantName: 'Spinach',
    plantType: 'Leafy green',
    plantDescription: 'A nutritious leafy green with tender leaves and mild flavor.',
    plantImage: '/images/spinach.png',
    plantWatering: 'Regular',
    plantLight: 'Partial shade',
    plantSoil: 'Rich, well-draining soil',
    plantFertilizer: 'Nitrogen-rich fertilizer',
    plantHumidity: 'Moderate',
    plantTemperature: '50-70°F (10-21°C)',
    plantToxicity: 'Non-toxic',
    plantPests: 'Aphids, leaf miners',
    plantDiseases: 'Downy mildew, leaf spot',
    spacing: 3,
    plantsPerSquareFoot: 16,
    color: '#304d3a',
  },
  {
    plantName: 'Strawberry',
    plantType: 'Fruit',
    plantDescription: 'A sweet, red fruit that grows on low-growing perennial plants.',
    plantImage: '/images/strawberry.png',
    plantWatering: 'Regular',
    plantLight: 'Full sun',
    plantSoil: 'Rich, well-draining soil',
    plantFertilizer: 'Balanced fertilizer',
    plantHumidity: 'Moderate',
    plantTemperature: '60-80°F (15-27°C)',
    plantToxicity: 'Non-toxic',
    plantPests: 'Slugs, aphids, spider mites',
    plantDiseases: 'Gray mold, leaf spot',
    spacing: 6,
    plantsPerSquareFoot: 4,
    color: '#e63946',
  },
  {
    plantName: 'Blueberry',
    plantType: 'Fruit',
    plantDescription: 'A perennial shrub that produces sweet, blue berries.',
    plantImage: '/images/blueberry.png',
    plantWatering: 'Regular',
    plantLight: 'Full sun',
    plantSoil: 'Acidic, well-draining soil',
    plantFertilizer: 'Acidic fertilizer',
    plantHumidity: 'Moderate',
    plantTemperature: '60-80°F (15-27°C)',
    plantToxicity: 'Non-toxic',
    plantPests: 'Blueberry maggots, aphids',
    plantDiseases: 'Mummy berry, powdery mildew',
    spacing: 18,
    plantsPerSquareFoot: 0.25,
    color: '#457b9d',
  },
  {
    plantName: 'Raspberry',
    plantType: 'Fruit',
    plantDescription: 'A perennial bush that produces sweet, red berries on canes.',
    plantImage: '/images/raspberry.png',
    plantWatering: 'Regular',
    plantLight: 'Full sun',
    plantSoil: 'Rich, well-draining soil',
    plantFertilizer: 'Balanced fertilizer',
    plantHumidity: 'Moderate',
    plantTemperature: '60-80°F (15-27°C)',
    plantToxicity: 'Non-toxic',
    plantPests: 'Japanese beetles, aphids',
    plantDiseases: 'Gray mold, cane blight',
    spacing: 18,
    plantsPerSquareFoot: 0.25,
    color: '#d00000',
  },
  {
    plantName: 'Watermelon',
    plantType: 'Fruit',
    plantDescription: 'A vining plant that produces large, juicy fruits with sweet red flesh.',
    plantImage: '/images/watermelon.png',
    plantWatering: 'Regular',
    plantLight: 'Full sun',
    plantSoil: 'Sandy, well-draining soil',
    plantFertilizer: 'Balanced fertilizer',
    plantHumidity: 'Moderate',
    plantTemperature: '70-90°F (21-32°C)',
    plantToxicity: 'Non-toxic',
    plantPests: 'Cucumber beetles, aphids',
    plantDiseases: 'Powdery mildew, fusarium wilt',
    spacing: 36,
    plantsPerSquareFoot: 0.25,
    color: '#6a994e',
  },
  {
    plantName: 'Cantaloupe',
    plantType: 'Fruit',
    plantDescription: 'A vining plant that produces sweet, orange-fleshed fruits with netted skin.',
    plantImage: '/images/cantaloupe.png',
    plantWatering: 'Regular',
    plantLight: 'Full sun',
    plantSoil: 'Sandy, well-draining soil',
    plantFertilizer: 'Balanced fertilizer',
    plantHumidity: 'Moderate',
    plantTemperature: '70-90°F (21-32°C)',
    plantToxicity: 'Non-toxic',
    plantPests: 'Cucumber beetles, aphids',
    plantDiseases: 'Powdery mildew, downy mildew',
    spacing: 36,
    plantsPerSquareFoot: 0.25,
    color: '#dda15e',
  },
  {
    plantName: 'Radish',
    plantType: 'Root vegetable',
    plantDescription: 'A fast-growing root vegetable with crisp, peppery flesh.',
    plantImage: '/images/radish.png',
    plantWatering: 'Regular',
    plantLight: 'Full sun',
    plantSoil: 'Loose, well-draining soil',
    plantFertilizer: 'Balanced fertilizer',
    plantHumidity: 'Moderate',
    plantTemperature: '55-75°F (13-24°C)',
    plantToxicity: 'Non-toxic',
    plantPests: 'Flea beetles, root maggots',
    plantDiseases: 'Downy mildew, black root',
    spacing: 3,
    plantsPerSquareFoot: 16,
    color: '#e5383b',
  },
  {
    plantName: 'Peas',
    plantType: 'Vegetable',
    plantDescription: 'A cool-season crop that produces sweet, edible seeds in pods.',
    plantImage: '/images/peas.png',
    plantWatering: 'Moderate',
    plantLight: 'Full sun',
    plantSoil: 'Rich, well-draining soil',
    plantFertilizer: 'Low-nitrogen fertilizer',
    plantHumidity: 'Moderate',
    plantTemperature: '55-70°F (13-21°C)',
    plantToxicity: 'Non-toxic',
    plantPests: 'Aphids, pea moths',
    plantDiseases: 'Powdery mildew, root rot',
    spacing: 4,
    plantsPerSquareFoot: 9,
    color: '#90be6d',
  },
  {
    plantName: 'Beans',
    plantType: 'Vegetable',
    plantDescription: 'A warm-season crop that produces edible pods or seeds.',
    plantImage: '/images/red-beans.png',
    plantWatering: 'Moderate',
    plantLight: 'Full sun',
    plantSoil: 'Well-draining, moderately rich soil',
    plantFertilizer: 'Low-nitrogen fertilizer',
    plantHumidity: 'Moderate',
    plantTemperature: '65-85°F (18-29°C)',
    plantToxicity: 'Some varieties have toxic raw beans',
    plantPests: 'Bean beetles, aphids',
    plantDiseases: 'Bacterial blight, rust',
    spacing: 4,
    plantsPerSquareFoot: 9,
    color: '#43aa8b',
  },
  {
    plantName: 'Okra',
    plantType: 'Vegetable',
    plantDescription: 'A warm-season vegetable with edible seed pods.',
    plantImage: '/images/okra.png',
    plantWatering: 'Regular',
    plantLight: 'Full sun',
    plantSoil: 'Rich, well-draining soil',
    plantFertilizer: 'Balanced fertilizer',
    plantHumidity: 'Moderate to high',
    plantTemperature: '70-95°F (21-35°C)',
    plantToxicity: 'Non-toxic',
    plantPests: 'Aphids, stink bugs',
    plantDiseases: 'Powdery mildew, leaf spot',
    spacing: 12,
    plantsPerSquareFoot: 1,
    color: '#588157',
  },
  {
    plantName: 'Brussels Sprouts',
    plantType: 'Vegetable',
    plantDescription: 'A cool-season vegetable with small, cabbage-like heads on a tall stalk.',
    plantImage: '/images/brussels-sprouts.png',
    plantWatering: 'Regular',
    plantLight: 'Full sun',
    plantSoil: 'Rich, well-draining soil',
    plantFertilizer: 'Nitrogen-rich fertilizer',
    plantHumidity: 'Moderate',
    plantTemperature: '45-75°F (7-24°C)',
    plantToxicity: 'Non-toxic',
    plantPests: 'Aphids, cabbage worms',
    plantDiseases: 'Black rot, clubroot',
    spacing: 18,
    plantsPerSquareFoot: 0.25,
    color: '#a7c957',
  },
  {
    plantName: 'Artichoke',
    plantType: 'Vegetable',
    plantDescription: 'A perennial vegetable with edible flower buds.',
    plantImage: '/images/artichoke.png',
    plantWatering: 'Regular',
    plantLight: 'Full sun',
    plantSoil: 'Rich, well-draining soil',
    plantFertilizer: 'Balanced fertilizer',
    plantHumidity: 'Moderate',
    plantTemperature: '55-75°F (13-24°C)',
    plantToxicity: 'Non-toxic',
    plantPests: 'Aphids, slugs',
    plantDiseases: 'Powdery mildew, botrytis',
    spacing: 36,
    plantsPerSquareFoot: 0.25,
    color: '#606c38',
  }
];

const seedDB = async () => {
  if (process.env.SEED_DATABASE === 'true') {
    try {
      // Connect to the database
      await db();
      console.log('Connected to the database');
      
      // Clear existing collections
      await cleanDB();
      console.log('Database cleared');
      
      // Seed plants
      await Plant.insertMany(plantSeeds);
      console.log(`${plantSeeds.length} plants inserted into database`);
      
      console.log('Database seeding completed successfully!');
      process.exit(0);
    
    } catch (err) {
      console.error('Error seeding database:', err);
      process.exit(1);
    }
  } else {
    console.log('Seeding skipped. Set SEED_DATABASE=true to seed the database.');
    process.exit(0);
  }
};
seedDB();